### ISSUE TITLE
Resources temporary unavailable

### ISSUE THREAD

**Issue by MohamadHarastani** [rosalindfranklininstitute/parakeet#54] opened 2023-08-23 12:59 UTC
Hello James
I was having an error related to h5py when running `parakeet.run -c config.yaml --steps all`. The error said "Resources temporary unavailable" and is related to a "locked" file. Something is not freeing the the h5 files, or maybe is a bug in the h5py. I worked around this error by pip install h5py==3.8.0
Cheers

**Comment by jmp1985** [comment] 2023-08-23 16:09
Hi Mohamad

That's really weird. I tried running the same command on a generic config file and I didn't have any issues. Can you send me the config file that showed this error?

I am also running h5py==3.8.0 at the moment but I will try updating and see if that breaks anything!

Best wishes
James

**Comment by MohamadHarastani** [comment] 2023-09-01 15:08
Hi James

Sorry for the late reply. I used to run this command with no issue, I reinstalled Parakeet and I was getting this problem sometimes (it's a tricky one). I have some config files that contain a lot of local structures that can reproduce the error, at least on my computer :-). If you wish, I can share them with you on email. But since I downgraded h5py everything is working fine. I'll keep this issue here just in case someone else faced this problem.

Cheers
Mohamad

**Comment by jmp1985** [comment] 2023-09-04 10:46
Hi Mohamad

Sure, if you can, send me the config files. I will try with the latest h5py on my machine and try and figure it out! But yes, until this is sorted it is best to keep the issue open!

Best wishes
James

**Comment by jmp1985** [comment] 2023-11-15 16:33
Hi Mohamad

I'm just going through trying to clear up a few issues. I decided to update all my packages and so now I am running with h5py 3.10. Everything seems to be working for me so I will close this issue.

If you get the issue again and find a way of reproducing it then we can re-open the issue.

Best wishes
James

**Closed by jmp1985** 2023-11-15 16:33 UTC
Labels: bug
